### ISSUE TITLE
Modlog Feature

### ISSUE THREAD

**Issue by Skillz4Killz** [KlasaCommunityPlugins/klasa-bot-plugin#7]
**Is your feature request related to a problem? Please describe.**
A way to review all mod logs where the moderator commands are run. Use a RichDisplay to show all these actions taken against a user.

.modlog USERID

Use user and not member so that users no longer in the server can be searched.

**Describe the solution you'd like**
1) A modlog command with a RD
2) A modlog channel posting all mod actions.
3) A command to remove a modlog from a user. `clearmodlog modLogID`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by WallyThePenguin** [comment]
Don't we have this available in ezlbot's repo? 
Maybe not richdisplay, but that would give us a headstart

**Comment by Skillz4Killz** [comment]
@WallyThePenguin make a PR with it please 🙏
